// Generated by Wrangler by running `wrangler types`

interface Env {
	FINANCIAL_DATASETS_API_KEY: string;
	OPENAI_API_KEY: string;
	ACCOUNT_ID: string;
	AI_GATEWAY_ID: string;
	AI_GATEWAY_TOKEN: string;
	INNGEST_SIGNING_KEY: string;
	INNGEST_EVENT_KEY: string;
	DB: D1Database;
}
