workers_dev = false
name = "simple-stock-screener"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

routes = [
  { pattern = "simple-stock-screener.ctoofeverything.dev", custom_domain = true }
]

[observability]
enabled = true