workers_dev = false
name = "simple-stock-screener"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat_v2"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

routes = [
  { pattern = "simple-stock-screener.ctoofeverything.dev", custom_domain = true }
]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "simple-stock-screener"
database_id = "2e183a38-13a0-46ab-954a-d5593291943d"
migrations_dir = "drizzle-migrations"

[[kv_namespaces]]
binding = "CACHE"
id = "068acc35637b41ba9063ac380c0a8f2b"
